import { Cairo } from "next/font/google";
import "./globals.css";
import ChatBot from "@/components/pageProps/charbot";
import ReduxProvider from "@/redux/providers";
import { cookies } from "next/headers";
import SessionProvider from "@/components/session/session-provider";
import { useSession } from "@/components/session/use-session";
import { checkAuth } from "@/components/pageProps/auth/check-Auth";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata = {
  title: "بصمة طبية",
  // description: "Generated by create next app",
    icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  const { user, success } = await checkAuth(token);

  const preloadedState = {
    auth: {
      user: user, // يتم الحفذ داخل ال authSlice in state
      isAuthenticated: success,
    },
  };
  return (
    <html lang="en">
      <body className={`${cairo.variable} antialiased`}>
        <div className="relative w-full">
          <ReduxProvider preloadedState={preloadedState}>
            <SessionProvider initialSession={token}>
              <div className="">{children}</div>
            </SessionProvider>
          </ReduxProvider>
          <ChatBot />
        </div>
      </body>
    </html>
  );
}
